/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anggi
 */
public class Quis2 extends javax.swing.JFrame {

    /**
     * Creates new form Quis2
     */
    public Quis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barang1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Barang2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Barang3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Barang4 = new javax.swing.JTextField();
        oke = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(158, 11, 70, 20);

        jLabel2.setText("Harga barang 1 ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 14);

        barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barang1ActionPerformed(evt);
            }
        });
        getContentPane().add(barang1);
        barang1.setBounds(140, 60, 170, 30);

        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 90, 30);

        Barang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Barang2ActionPerformed(evt);
            }
        });
        getContentPane().add(Barang2);
        Barang2.setBounds(140, 130, 170, 30);

        jLabel4.setText("Harga Barang  3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 100, 14);

        Barang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Barang3ActionPerformed(evt);
            }
        });
        getContentPane().add(Barang3);
        Barang3.setBounds(140, 200, 170, 30);

        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 270, 100, 14);

        Barang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Barang4ActionPerformed(evt);
            }
        });
        getContentPane().add(Barang4);
        Barang4.setBounds(140, 260, 180, 30);

        oke.setText("Submit");
        oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeActionPerformed(evt);
            }
        });
        getContentPane().add(oke);
        oke.setBounds(20, 370, 80, 23);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 370, 80, 23);

        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 370, 90, 23);

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 400, 350, 130);

        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 330, 70, 14);
        getContentPane().add(diskon);
        diskon.setBounds(140, 320, 180, 30);

        setBounds(0, 0, 416, 583);
    }// </editor-fold>//GEN-END:initComponents

    private void barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barang1ActionPerformed

    private void Barang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Barang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Barang2ActionPerformed

    private void Barang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Barang3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Barang3ActionPerformed

    private void Barang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Barang4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Barang4ActionPerformed

    private void okeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeActionPerformed
        // TODO add your handling code here:
        int Barang1 = Integer.parseInt(barang1.getText());
        int barang2 = Integer.parseInt(Barang2.getText());
        int barang3 = Integer.parseInt(Barang3.getText());
        int barang4 = Integer.parseInt(Barang4.getText());
        int Diskon = Integer.parseInt(diskon.getText());
        
        int TH = Barang1 + barang2 + barang3 + barang4;
        int diskon = (TH*Diskon)/100;
        int TB = TH - diskon;
        
        ta.setText("Harga Barang 1 : "+Barang1+"\nHarga barang 2 : "+barang2+"\nHarga barang3 : "+barang3+
                "\nHarga barang4"+barang4+"\nDiskon : "+Diskon+"\nTotal Harga : "+TH+"\nTotal Bayar : "+TB);
        
    }//GEN-LAST:event_okeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Barang2;
    private javax.swing.JTextField Barang3;
    private javax.swing.JTextField Barang4;
    private javax.swing.JTextField barang1;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton oke;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
